---
transports:
  - driver: redis
    url: redis://user:pass@localhost:6379/0

  - driver: nats
    url: nats://user:pass@localhost:4222/heimdall?queue_group=prod

  - driver: nats
    url: nats://user:pass@localhost:4222/heimdall?queue_group=dev